from environs import Env

env = Env()
env.read_env()

BOT_TOKEN = env('BOT_TOKEN')
ADMIN = env('ADMIN')
BASE_URL = env('BASE_URL')
PASSPORT_ID_IMAGE = env('PASSPORT_ID_IMAGE')
PASSPORT_JSH_IMAGE = env('PASSPORT_JSH_IMAGE')
PASSPORT_FRONT_IMAGE = env('PASSPORT_FRONT_IMAGE')
PASSPORT_BACK_IMAGE = env('PASSPORT_BACK_IMAGE')
